In [22]:
import requests
import pandas as pd
import configparser  
config = configparser.ConfigParser() 
config.read("C:/Users/tomas/Dropbox/Prop-Trading Business/oanda.cfg") 

api_key         =  config["oanda"]['api_key']
oanda_api_url   =  config["oanda"]['oanda_api_url']
account_id      =  config["oanda"]['account_id']
headers         = {'Authorization': f'Bearer {api_key}'}
my_url          = "https://api-fxpractice.oanda.com"
session         = requests.Session()

In [38]:
def GetCandleData(headers,symbol,granularity,price,count):
    """
    Function type: Api Data Request
    Fetch candlestick data for an instrument
    """
    try:
        response = session.get(f"{my_url}/v3/instruments/"+symbol+"/candles",headers=headers, params={"granularity":granularity,"price":price,"count":count })
        data = response.json()
        print(response.status_code)
    except:
        print(response.status_code)
    return data

In [54]:
data = GetCandleData(headers,"EUR_USD",granularity="H1",price="MBA",count=800)

200

In [59]:
def GetCandlesDataFrame(json_response):
    prices = ["mid", "bid", "ask"]
    ohlc = ["o","h","l","c"]
    our_data = []
    for candle in data["candles"]:
        if candle["complete"] == False:
            continue
        new_dict = {}
        new_dict["time"] = candle["time"]
        new_dict["volume"] = candle["volume"]
        for price in prices:
            for oh in ohlc:
                new_dict[f"{price}_{oh}"] = candle[price][oh]
        our_data.append(new_dict)
    candles_df = pd.DataFrame(our_data)
    return candles_df

In [60]:
GetCandlesDataFrame(data)
#candles_df.to_csv("Candle_data.csv")

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2021-09-16T15:00:00.000000000Z,4166,1.17628,1.17670,1.17554,1.17634,1.17621,1.17663,1.17547,1.17626,1.17635,1.17678,1.17561,1.17641
1,2021-09-16T16:00:00.000000000Z,2162,1.17632,1.17644,1.17584,1.17596,1.17624,1.17638,1.17578,1.17590,1.17640,1.17651,1.17590,1.17603
2,2021-09-16T17:00:00.000000000Z,1741,1.17598,1.17615,1.17538,1.17556,1.17591,1.17609,1.17532,1.17550,1.17605,1.17622,1.17544,1.17563
3,2021-09-16T18:00:00.000000000Z,1683,1.17558,1.17572,1.17537,1.17540,1.17551,1.17566,1.17530,1.17533,1.17565,1.17579,1.17543,1.17547
4,2021-09-16T19:00:00.000000000Z,4454,1.17541,1.17716,1.17534,1.17690,1.17534,1.17708,1.17527,1.17684,1.17548,1.17723,1.17541,1.17697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,2021-11-02T17:00:00.000000000Z,2162,1.15781,1.15846,1.15770,1.15832,1.15773,1.15840,1.15762,1.15825,1.15789,1.15853,1.15777,1.15840
795,2021-11-02T18:00:00.000000000Z,1967,1.15831,1.15855,1.15771,1.15816,1.15824,1.15848,1.15764,1.15809,1.15838,1.15862,1.15778,1.15823
796,2021-11-02T19:00:00.000000000Z,1637,1.15815,1.15841,1.15796,1.15834,1.15808,1.15833,1.15788,1.15826,1.15822,1.15849,1.15804,1.15842
797,2021-11-02T20:00:00.000000000Z,618,1.15832,1.15832,1.15786,1.15799,1.15824,1.15824,1.15778,1.15790,1.15840,1.15840,1.15794,1.15808
798,2021-11-02T21:00:00.000000000Z,97,1.15788,1.15820,1.15760,1.15786,1.15767,1.15801,1.15724,1.15764,1.15809,1.15854,1.15780,1.15809